SELECT S.USN, S.Name, COUNT(BO.Bookid) AS NumBooks  
FROM STUDENT S 
JOIN BORROW BO ON S.USN = BO.USN 
GROUP BY S.USN, S.Name 
HAVING COUNT(BO.Bookid) > 2; 



SELECT S.USN, S.Name 
FROM STUDENT S 
JOIN BORROW BO ON S.USN = BO.USN 
JOIN BOOK BK ON BO.Bookid = BK.Bookid 
GROUP BY S.USN, S.Name 
HAVING COUNT(DISTINCT BK.Authorid) > 1; 
